library(readxl)
library(openxlsx)
require(tidyr)
require(readr)

podatkiZDA20 <- read_xlsx('projekt/ZDA20.xlsx')
podatkiSLO20 <- read_xlsx('projekt/SLO20.xlsx')
podatkiZDA19 <- read_xlsx('projekt/ZDA19.xlsx')
podatkiSLO19 <- read_xlsx('projekt/SLO19.xlsx')
podatkiZDA18 <- read_xlsx('projekt/ZDA18.xlsx')
podatkiSLO18 <- read_xlsx('projekt/SLO18.xlsx')
podatkiZDA17 <- read_xlsx('projekt/ZDA17.xlsx')
podatkiSLO17 <- read_xlsx('projekt/SLO17.xlsx')
podatkiZDA16 <- read_xlsx('projekt/ZDA16.xlsx')
podatkiSLO16 <- read_xlsx('projekt/SLO16.xlsx')
podatkiZDA15 <- read_xlsx('projekt/ZDA15.xlsx')
podatkiSLO15 <- read_xlsx('projekt/SLO15.xlsx')
podatkiZDA09 <- read_xlsx('projekt/ZDA09.xlsx')
podatkiSLO09 <- read_xlsx('projekt/SLO09.xlsx')
podatkiZDA08 <- read_xlsx('projekt/ZDA08.xlsx')
podatkiSLO08 <- read_xlsx('projekt/SLO08.xlsx')
podatkiZDA07 <- read_xlsx('projekt/ZDA07.xlsx')
podatkiSLO07 <- read_xlsx('projekt/SLO07.xlsx')

library(dplyr)

podatkiZDA20 <- podatkiZDA20 %>% mutate(Leto = 2020) %>% drop_na(Mesto)
podatkiSLO20 <- podatkiSLO20 %>% mutate(Leto = 2020) %>% drop_na(Mesto)
podatkiZDA19 <- podatkiZDA19 %>% mutate(Leto = 2019) %>% drop_na(Mesto)
podatkiSLO19 <- podatkiSLO19 %>% mutate(Leto = 2019) %>% drop_na(Mesto)
podatkiZDA18 <- podatkiZDA18 %>% mutate(Leto = 2018) %>% drop_na(Mesto)
podatkiSLO18 <- podatkiSLO18 %>% mutate(Leto = 2018) %>% drop_na(Mesto)
podatkiZDA17 <- podatkiZDA17 %>% mutate(Leto = 2017) %>% drop_na(Mesto)
podatkiSLO17 <- podatkiSLO17 %>% mutate(Leto = 2017) %>% drop_na(Mesto)
podatkiZDA16 <- podatkiZDA16 %>% mutate(Leto = 2016) %>% drop_na(Mesto)
podatkiSLO16 <- podatkiSLO16 %>% mutate(Leto = 2016) %>% drop_na(Mesto)
podatkiZDA15 <- podatkiZDA15 %>% mutate(Leto = 2015) %>% drop_na(Mesto)
podatkiSLO15 <- podatkiSLO15 %>% mutate(Leto = 2015) %>% drop_na(Mesto)
podatkiZDA09 <- podatkiZDA09 %>% mutate(Leto = 2009) %>% drop_na(Mesto)
podatkiSLO09 <- podatkiSLO09 %>% mutate(Leto = 2009) %>% drop_na(Mesto)
podatkiZDA08 <- podatkiZDA08 %>% mutate(Leto = 2008) %>% drop_na(Mesto)
podatkiSLO08 <- podatkiSLO08 %>% mutate(Leto = 2008) %>% drop_na(Mesto)
podatkiZDA07 <- podatkiZDA07 %>% mutate(Leto = 2007) %>% drop_na(Mesto)
podatkiSLO07 <- podatkiSLO07 %>% mutate(Leto = 2007) %>% drop_na(Mesto)

require(rvest)
url <- "https://www.the-numbers.com/market/2019/genre/Adventure"

stran <- read.html(url)
stran %>% html_nodes(xpath="//table") %>% html_table()
