library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(XML)
library(stringr)
library(tibble)
library(quantmod)
library(tidyverse)
library(Quandl)
library(ggplot2)
library(shiny)
library(shinythemes)
library(mgcv)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
