library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(readxl)
library(openxlsx)
require(ggplot2)
require(rvest)
require(xml2)
require(stringr)
require(maptools)
require(rgdal)
require(rgeos)
require(janitor)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
